<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Domain.Certificates\Domain.Certificates.csproj" />
        <ProjectReference Include="..\Domain.Proxy\Domain.Proxy.csproj" />
        <ProjectReference Include="..\Domain.Rules\Domain.Rules.csproj" />
        <ProjectReference Include="..\Domain.Scripting\Domain.Scripting.csproj" />
        <ProjectReference Include="..\Domain.Throttling\Domain.Throttling.csproj" />
        <ProjectReference Include="..\Domain.Traffic\Domain.Traffic.csproj" />
        <ProjectReference Include="..\Framework.Networking\Framework.Networking.csproj" />
        <ProjectReference Include="..\Framework.Platform\Framework.Platform.csproj" />
        <ProjectReference Include="..\Framework.Serialization\Framework.Serialization.csproj" />
    </ItemGroup>

</Project>
