<Project>

    <PropertyGroup>
        <ProductName>Proxyfan</ProductName>
        <RootNamespace>$(ProductName).$(MSBuildProjectName)</RootNamespace>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Environment Condition=" '$(Environment)' == '' ">Development</Environment>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Environment)' != '' ">
        <DefineConstants>$(DefineConstants);ENVIRONMENT_$(Environment.ToUpper())</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="all" />
        <PackageReference Include="Automaticks.CSharp.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Automaticks.Threading.Tasks.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Automaticks.Linq.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Automaticks.Reflection.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Automaticks.Extensions.Options.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Automaticks.Diagnostics.CodeAnalysis.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Automaticks.CommunityToolkit.Mvvm.Analyzers" PrivateAssets="all" />
    </ItemGroup>

</Project>