<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TestingPlatformCommandLineArguments>--ignore-exit-code 8</TestingPlatformCommandLineArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Domain.RemoteDevices\Domain.RemoteDevices.csproj" />
        <ProjectReference Include="..\..\src\Domain\Domain.csproj" />
        <ProjectReference Include="..\..\src\Domain.Traffic\Domain.Traffic.csproj" />
    </ItemGroup>

</Project>
