<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TestingPlatformCommandLineArguments>--ignore-exit-code 8</TestingPlatformCommandLineArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="TngTech.ArchUnitNET" />
        <PackageReference Include="TngTech.ArchUnitNET.TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Domain.Configuration\Domain.Configuration.csproj" />
        <ProjectReference Include="..\..\src\Domain.Traffic\Domain.Traffic.csproj" />
        <ProjectReference Include="..\..\src\Framework.Serialization\Framework.Serialization.csproj" />
    </ItemGroup>

</Project>
