<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TestingPlatformCommandLineArguments>--ignore-exit-code 8</TestingPlatformCommandLineArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="TUnit" />
        <PackageReference Include="TngTech.ArchUnitNET.TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Clients\Client\Client.csproj" />
    </ItemGroup>

</Project>