<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TestingPlatformCommandLineArguments>--ignore-exit-code 8</TestingPlatformCommandLineArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="TUnit" />
        <PackageReference Include="TngTech.ArchUnitNET.TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Clients\Client\Client.csproj" />
        <ProjectReference Include="..\..\src\Domain.Configuration\Domain.Configuration.csproj" />
        <ProjectReference Include="..\..\src\Domain.DomainNameSystemSpoofing\Domain.DomainNameSystemSpoofing.csproj" />
        <ProjectReference Include="..\..\src\Domain.RemoteDevices\Domain.RemoteDevices.csproj" />
        <ProjectReference Include="..\..\src\Framework.Extensibility\Framework.Extensibility.csproj" />
        <ProjectReference Include="..\..\src\Plugin.Abstractions\Plugin.Abstractions.csproj" />
    </ItemGroup>

</Project>