<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TestingPlatformCommandLineArguments>--ignore-exit-code 8</TestingPlatformCommandLineArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="TngTech.ArchUnitNET" />
        <PackageReference Include="TngTech.ArchUnitNET.TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Cli\Cli.csproj" />
        <ProjectReference Include="..\..\src\Domain.Rules\Domain.Rules.csproj" />
    </ItemGroup>

</Project>
