name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build & test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          ./.tools/Invoke-Build.ps1 -Configuration Debug

      - name: Test
        shell: pwsh
        run: |
          ./.tools/Run-Tests.ps1 -Configuration Debug -NoBuild
